using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using PersonalProject;

namespace PersonalProject
{
    public class Pokedex
    {
        public List<Pokemon> pokemons { get; set; }

        public Pokedex()
        {
            pokemons = new List<Pokemon>();
            pokemons.Add(new Pokemon("Bulbasaur", 0.7, 6.9, "Seed", "Overgrow", "Grass & Poison", 1, "Ivysaur", "At the beginning of its life, it feeds on the nutrients stored in the seed on its back. This allows it to grow", 1, "Classified as a Grass- and Poison-type Pokémon, Bulbasaur is one of three starter Pokémon players are able to select at the game's beginning. It is a quadrupedal green creature resembling a dinosaur, with a large plant bulb on its back. Bulbasaur is a central character in the Pokémon anime, being one of Ash Ketchum's main Pokémon for the first season, with a different one later obtained by supporting character May. It is featured in various manga and is owned by protagonist Red in Pokémon Adventures.\r\n\r\nBulbasaur is generally considered one of the most popular and widely liked Pokémon, having ranked highly in official popularity polls.[5] Series producer Junichi Masuda has also specifically mentioned Bulbasaur as one of his favorite Pokémon. Its role in the anime has been suggested to have played a factor into its popularity."));
            pokemons.Add(new Pokemon("Ivysaur", 1.0, 13.0, "Seed", "Overgrow", "Grass & Poison", 1, "Venusaur", "The more it is exposed to the sun, the more energy it stores, which allows the bud on its back to develop.", 2, "Ivysaur are able to naturally learn the powerful Grass-type attack Solar Beam, a move whose execution time depends largely upon the weather; it takes an excruciatingly long amount of time to perform this attack in hail, rain, or a sandstorm, but nearly no time at all in bright sunlight. Luckily, the latter is ​most common in the habitats of these Pokémon, as it is vital that the bulbs on their backs receive ample sunlight so that they can photosynthesize and develop. As the bulbs grow larger and these Ivysaur become more powerful, they must spend increasing amounts of time in the sun in order to foster their growth. When Ivysaur are preparing to evolve into Venusaur, they will spend more time sunbathing and their bulbs will begin emanating a sweet, pleasant aroma."));
            pokemons.Add(new Pokemon("Venusaur", 2.0, 100.0, "Seed", "Overgrow", "Grass & Poison", 1, "None", "This Pokémon is capable of transforming sunlight into energy. It is therefore even stronger in summer.", 3, "Venusaur absorbs sunlight to gain energy and to feed its flower, located on its back. After gaining a certain amount of sunlight, the flower will release a sweet aroma said to soothe the emotions of people. Additionally, after a rainy day, the smell of the flower's aroma grows stronger, attracting other Pokémon.\r\n\r\nThe power of Gigantamaxing has made Venusaur's flower bloom so large that it covers the Pokémon's body. The flower's petals are extremely thick and springy enough to repel halfhearted attacks. During battle, the Pokémon uses these petals as a shield and swings its two thick vines around to attack its target.\r\n\r\nThe flower on the Pokémon's back spews so much pollen that it resembles a volcanic eruption. Inhaling the pollen can cause uncontrollable sneezing, and breathing in too much of it can even cause fainting. However, the pollen also stimulates plant growth. Places where the pollen falls are said to grow thick with large plants."));
            pokemons.Add(new Pokemon("Charmander", 0.6, 8.5, "Lizard", "Brasier", "Fire", 1, "Charmeleon", "The flame at the end of its tail represents its vitality. When it is not at its best, it weakens.", 4, "Charmander is easily the most mild-mannered and well-behaved of its evolution line. Its feelings and emotions can be read by the flame on the tip of its tail. It flares up in a fury when Charmander is angry. The flame will flicker and grow small and dim if Charmander is sick or hurt. If it growls, that means it's angry or is about to attack.\r\n\r\nCharmander, however, doesn't do well with impatient people. It doesn't appreciate being rushed, and most of the time, will not allow it. It is a sweet Pokémon, but is feisty nonetheless. Charmander doesn't enjoy accepting favors, because it feels it owes something in return. It is extremely loyal to its loved ones, and knows a good thing when it sees it. It will treat those in its life accordingly.\r\n\r\nCharmander is rarely found in the wild since it's a first partner Pokémon. Sometimes they gather in extremely hot areas such as active volcanoes or in craggy mountains and in caves along the coast of the Sevii Islands."));
            pokemons.Add(new Pokemon("Charmeleon", 1.1, 19.0, "Flamme", "Brasier", "Fire", 1, "Charizard", "By waving its flaming tail, it can exponentially raise the ambient temperature and thus torment its opponents.", 5, "Charmeleon, like its other evolutionary forms, can naturally breathe fire. Its powers, though, are much greater than Charmander's, but not as great as Charizard's.\r\n\r\nCharmeleon is also much more aggressive than Charmander. It is believed to have a vicious nature and will constantly seek out opponents. Strong opponents excite this Pokémon, causing it to spout bluish-white flames that torch its surroundings. It is a very ruthless, pitiless and zealous fighter often using its claws. However, it will relax once it has won.\r\n\r\nIn their fervor, their tails often begin to burn a bluish-white; at night, they can light up mountainsides like stars if groups of them are present. Enraged Charmeleon often take out their anger on their surroundings, incinerating anything flammable around them with unrestrained Flamethrowers.\r\n\r\nThis stage is often likened to a human’s teenage years--moody and reckless. Charmander and Charizard, can be found in hot, rocky mountainous areas."));
            pokemons.Add(new Pokemon("Charizard", 1.7, 90.5, "Flamme", "Brasier", "Fire & Flying", 1, "None", "When he gets really angry, the flame at the end of his tail turns blue.", 6, "Charizard are noble and will not turn the full power of their flame on opponents significantly weaker than themselves. They are also known to be very eager to battle. Charizard seeks out stronger foes and only breathes fire during battles with worthy opponents. The fiery breath is so hot that it can turn any material to slag. They can be very dangerous and aggressive if provoked, but like its previous evolutions, Charizard is generally friendly and loyal to a skilled Trainer. Charizard only ignores its Trainer if it feels that they do not care about it.\r\n\r\nIn the anime, only a weak or poorly trained Charizard actively shows off its power, as said by Liza in \"Charizard's Burning Ambitions\". In rare cases, Charizard will evolve from a less civilized Charmeleon and keep an un-preferable behavior. In any such cases, training will work but will be difficult."));

        }
    }
}
